//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeServiceRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeRate", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchangeOffice.Service")]
    public partial class ExchangeRate : object
    {
        
        private decimal BuyRateField;
        
        private string CurrencyCodeField;
        
        private string CurrencyNameField;
        
        private string DateField;
        
        private decimal SellRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BuyRate
        {
            get
            {
                return this.BuyRateField;
            }
            set
            {
                this.BuyRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyName
        {
            get
            {
                return this.CurrencyNameField;
            }
            set
            {
                this.CurrencyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SellRate
        {
            get
            {
                return this.SellRateField;
            }
            set
            {
                this.SellRateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoricalRate", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchangeOffice.Service")]
    public partial class HistoricalRate : object
    {
        
        private string DateField;
        
        private decimal MidRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MidRate
        {
            get
            {
                return this.MidRateField;
            }
            set
            {
                this.MidRateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchangeOffice.Service")]
    public partial class UserDto : object
    {
        
        private string EmailField;
        
        private string MessageField;
        
        private bool SuccessField;
        
        private int UserIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountBalance", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchangeOffice.Service")]
    public partial class AccountBalance : object
    {
        
        private System.Collections.Generic.Dictionary<string, decimal> CurrenciesField;
        
        private decimal PLNField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, decimal> Currencies
        {
            get
            {
                return this.CurrenciesField;
            }
            set
            {
                this.CurrenciesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PLN
        {
            get
            {
                return this.PLNField;
            }
            set
            {
                this.PLNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionResult", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchangeOffice.Service")]
    public partial class TransactionResult : object
    {
        
        private string MessageField;
        
        private decimal NewPLNBalanceField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NewPLNBalance
        {
            get
            {
                return this.NewPLNBalanceField;
            }
            set
            {
                this.NewPLNBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionDto", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchangeOffice.Service")]
    public partial class TransactionDto : object
    {
        
        private decimal AmountField;
        
        private string CurrencyCodeField;
        
        private string DateField;
        
        private decimal PLNValueField;
        
        private decimal RateField;
        
        private int TransactionIdField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PLNValue
        {
            get
            {
                return this.PLNValueField;
            }
            set
            {
                this.PLNValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate
        {
            get
            {
                return this.RateField;
            }
            set
            {
                this.RateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExchangeServiceRef.IExchangeService")]
    public interface IExchangeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/GetCurrentRate", ReplyAction="http://tempuri.org/IExchangeService/GetCurrentRateResponse")]
        System.Threading.Tasks.Task<ExchangeServiceRef.ExchangeRate> GetCurrentRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/GetAllRates", ReplyAction="http://tempuri.org/IExchangeService/GetAllRatesResponse")]
        System.Threading.Tasks.Task<ExchangeServiceRef.ExchangeRate[]> GetAllRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/GetHistoricalRates", ReplyAction="http://tempuri.org/IExchangeService/GetHistoricalRatesResponse")]
        System.Threading.Tasks.Task<ExchangeServiceRef.HistoricalRate[]> GetHistoricalRatesAsync(string currencyCode, string startDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/RegisterUser", ReplyAction="http://tempuri.org/IExchangeService/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(string username, string passwordHash, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/LoginUser", ReplyAction="http://tempuri.org/IExchangeService/LoginUserResponse")]
        System.Threading.Tasks.Task<ExchangeServiceRef.UserDto> LoginUserAsync(string username, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/GetBalance", ReplyAction="http://tempuri.org/IExchangeService/GetBalanceResponse")]
        System.Threading.Tasks.Task<ExchangeServiceRef.AccountBalance> GetBalanceAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/TopUpAccount", ReplyAction="http://tempuri.org/IExchangeService/TopUpAccountResponse")]
        System.Threading.Tasks.Task<bool> TopUpAccountAsync(int userId, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/BuyCurrency", ReplyAction="http://tempuri.org/IExchangeService/BuyCurrencyResponse")]
        System.Threading.Tasks.Task<ExchangeServiceRef.TransactionResult> BuyCurrencyAsync(int userId, string currencyCode, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/SellCurrency", ReplyAction="http://tempuri.org/IExchangeService/SellCurrencyResponse")]
        System.Threading.Tasks.Task<ExchangeServiceRef.TransactionResult> SellCurrencyAsync(int userId, string currencyCode, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/GetTransactionHistory", ReplyAction="http://tempuri.org/IExchangeService/GetTransactionHistoryResponse")]
        System.Threading.Tasks.Task<ExchangeServiceRef.TransactionDto[]> GetTransactionHistoryAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IExchangeServiceChannel : ExchangeServiceRef.IExchangeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ExchangeServiceClient : System.ServiceModel.ClientBase<ExchangeServiceRef.IExchangeService>, ExchangeServiceRef.IExchangeService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ExchangeServiceClient() : 
                base(ExchangeServiceClient.GetDefaultBinding(), ExchangeServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IExchangeService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ExchangeServiceClient.GetBindingForEndpoint(endpointConfiguration), ExchangeServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ExchangeServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ExchangeServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ExchangeServiceRef.ExchangeRate> GetCurrentRateAsync(string currencyCode)
        {
            return base.Channel.GetCurrentRateAsync(currencyCode);
        }
        
        public System.Threading.Tasks.Task<ExchangeServiceRef.ExchangeRate[]> GetAllRatesAsync()
        {
            return base.Channel.GetAllRatesAsync();
        }
        
        public System.Threading.Tasks.Task<ExchangeServiceRef.HistoricalRate[]> GetHistoricalRatesAsync(string currencyCode, string startDate, string endDate)
        {
            return base.Channel.GetHistoricalRatesAsync(currencyCode, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(string username, string passwordHash, string email)
        {
            return base.Channel.RegisterUserAsync(username, passwordHash, email);
        }
        
        public System.Threading.Tasks.Task<ExchangeServiceRef.UserDto> LoginUserAsync(string username, string passwordHash)
        {
            return base.Channel.LoginUserAsync(username, passwordHash);
        }
        
        public System.Threading.Tasks.Task<ExchangeServiceRef.AccountBalance> GetBalanceAsync(int userId)
        {
            return base.Channel.GetBalanceAsync(userId);
        }
        
        public System.Threading.Tasks.Task<bool> TopUpAccountAsync(int userId, decimal amount)
        {
            return base.Channel.TopUpAccountAsync(userId, amount);
        }
        
        public System.Threading.Tasks.Task<ExchangeServiceRef.TransactionResult> BuyCurrencyAsync(int userId, string currencyCode, decimal amount)
        {
            return base.Channel.BuyCurrencyAsync(userId, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<ExchangeServiceRef.TransactionResult> SellCurrencyAsync(int userId, string currencyCode, decimal amount)
        {
            return base.Channel.SellCurrencyAsync(userId, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<ExchangeServiceRef.TransactionDto[]> GetTransactionHistoryAsync(int userId)
        {
            return base.Channel.GetTransactionHistoryAsync(userId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IExchangeService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IExchangeService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:3075/ExchangeService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ExchangeServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IExchangeService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ExchangeServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IExchangeService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IExchangeService,
        }
    }
}
